# Generated by Django 5.0.6 on 2024-05-26 12:03

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='history_price_dates_3years',
            field=store.models.JSONFileField(upload_to='media/jsons'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prediction_price_date',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='history_buys',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='list_buy_in_shopping_cart',
            field=models.JSONField(default=list),
        ),
    ]
