# Generated by Django 5.0.6 on 2024-05-26 12:44

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_history_price_dates_3years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='history_price_dates_3years',
            field=store.models.JSONFileField(default=dict, upload_to='media/jsons'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prediction_price_date',
            field=models.JSONField(default=dict),
        ),
    ]
